---
title: "Problem Set 1"
author:
  - Your Name Here
format: 
  html:
    code-fold: true
    embed-resources: true
    toc: true
    toc-depth: 2
    toc-title: Contents
---

## Important packages you will need for this course

The following are packages you will need for this class: 
  - tidyverse
  - cowplot
  - patchwork
  - paleteer

Install these packages using `install.packages()` in the R console (e.g. `install.packages("tidyverse", dep = TRUE))`. Remember you only need to do this once and then you will use `library()` to load them. If you already have these packages, update them to the latest version using the same `install.packages()` function.

Once the installations are complete, write your setup chunk below loading these four packages using `library()`. Also load the cowplot theme using the following: `theme_set(theme_cowplot())`. You will use this same setup chunk with some possible additions for most problem sets. Including the options for echo, message, and warning means it won't print anything from this part in the html output. 

```{r}
#| echo: false
#| message: false
#| warning: false

#[FIXME]
library(tidyverse)
library(cowplot)
library(patchwork)
library(paletteer)

theme_set(theme_cowplot())

```

## Outline

1.
- give stats - what do you conclude? Then plot and now what?

2.
- What does this plot say? - What would you conclude? Different versions of a figure?

3. 
- here is a question. how would a plot show the answer?

4.
- Dataset 
  - plot that needs long format
  - plot that needs wide format

5. Separate or unite 

6.
- Dataset 
  - plot that reveals data problems
  - do some cleaning

7.
- Dataset
  - lots of geoms
  
8. find a terrible image from lit - explain why - give link



