---
title: "Problem Set 2"
author:
  - Your Name Here
format: 
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
    toc-title: Contents
---

```{r}
#| echo: false
#| message: false

library(tidyverse)
library(cowplot)

theme_set(theme_cowplot())

# Required files for this problem set:

```


## Prove the central limit theorem

```{r}
SP <- abdData::SticklebackPlates

ggplot(SP, aes(plates)) +
  geom_histogram(bins = 30) +
  facet_grid(genotype ~ .)

SP |> 
  group_by(genotype) |> 
  summarize(Mean = mean(plates),
            Median = median(plates))

Mm <- SP |> 
  filter(genotype == "Mm") |> 
  pull(plates)

resample_Mm <- function(ii, nsamp) {
  ids <- sample(seq_len(length(Mm)), nsamp)
  return(tibble(ii, bar = mean(Mm[ids])))
}

niter <- 1000
resamples <- map(.x = seq_len(niter),
                 .f = resample_Mm,
                 nsamp = 20) |> 
  list_rbind()

ggplot(resamples, aes(bar)) +
  geom_histogram(bins = 30)

mean(resamples$bar)
median(Mm)

```


```{r}
library(boot)

mean_fun <- function(data, indices) {
  data_sub <- data[indices]
  return(mean(data_sub))
}

b <- boot(data = Mm, statistic = mean_fun, R = 2000, stype = "i")
b
plot(b)
boot.ci(b, type="bca")
```

