---
title: "Randomization and Simulation Methods"
subtitle: "Introduction"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
---

## Module overview

```{r}
#| label: setup
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(cowplot)
ggplot2::theme_set(theme_cowplot())
```

1. Core concepts: In what ways is random sampling useful for data analysis?
2. Sampling from data sets: foundations
3. Sampling from data sets: complex designs
4. Sampling from data sets: decision errors and predicting new data
5. Simulating data for inference


## Module prerequisites

- *Quantitative Methods in Life Sciences I*
- Updated R and RStudio
- Basics of probability and statistics
- Basics of R programming methods


## Relevant *Quantitative Methods I* course materials

- Foundational Concepts in Probability & Statistics: Weeks 4, 5, 6, & 7
- Unit 10: Cross Validation (10-4)
- Unit 12: Randomization (12-3)
- [Course files on Github](https://github.com/kmiddleton/quant_methods)
  - Clone to your computer for reference
- [Course videos on Youtube](https://www.youtube.com/playlist?list=PLeIk-G-wZpqx1yW49XAHqoccBXhNJrUSu) 


## Resources

- [R for Data Science](https://r4ds.had.co.nz/)
- [Tidyverse style guide](https://style.tidyverse.org/)
- [Randomization, Bootstrap and Monte Carlo Methods in Biology](https://www.amazon.com/Randomization-Bootstrap-Methods-Biology-Statistical-dp-0367349949/dp/0367349949/)
- [Computer-Intensive Methods of Data Analysis in Biology](https://www.cambridge.org/core/books/introduction-to-computerintensive-methods-of-data-analysis-in-biology/4258A90A73B35675ECBAC6B57EDB0B5A)
- [Introduction to Modern Statistics](https://openintro-ims.netlify.app/index.html)
- [An Introduction to Statistical Learning](https://www.statlearning.com/)


## What we cover and don't cover

Do:

- Many scenarios where random sampling is useful
- Common cases you will encounter
    - How to use these methods in place of "standard" statistical analyses

Don't:

- Every possible use case
    - Endless possible questions and applications


## Multiple motivations for this module

1. Demystify the workings & philosophy of statistical tests
2. Empower you to explore and simulate your data sets
3. Allow you to set up tests of the questions you might have about a method


## Target Skillsets

- Statistical understanding
- Programming
- Simulating and evaluating data
- Methods for parallel processing


## Useful Packages

- [purrr](https://purrr.tidyverse.org/index.html) 
    - part of [tidyverse](https://www.tidyverse.org/)
- [boot](https://cran.r-project.org/web/packages/boot/boot.pdf)
- [bootstrap](https://cran.r-project.org/web/packages/bootstrap/bootstrap.pdf)
- [cvTools](https://cran.r-project.org/web/packages/cvTools/cvTools.pdf)
- [caret](http://topepo.github.io/caret/index.html)
- [future](https://future.futureverse.org/)
    - [furrr](https://furrr.futureverse.org/)
